# Generated by Django 2.1.3 on 2018-11-29 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('apartamentoId', models.AutoField(primary_key=True, serialize=False)),
                ('bloco', models.CharField(max_length=5)),
                ('andar', models.IntegerField()),
                ('numero', models.CharField(max_length=5)),
                ('tamanho', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('dispositivoId', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=150)),
                ('modelo', models.CharField(max_length=150)),
                ('dataInstalacao', models.DateField()),
                ('apartamentoId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Apartamento')),
            ],
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('edificioId', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('dataConstrucao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('enderecoId', models.AutoField(primary_key=True, serialize=False)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('complemento', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=15)),
                ('edificioId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Edificio')),
            ],
        ),
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('medicaoId', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField()),
                ('valorMedido', models.DecimalField(decimal_places=2, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMedicao',
            fields=[
                ('tipoMedicaoId', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('unidadeMedida', models.CharField(max_length=5)),
                ('valorPorUnidade', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.AddField(
            model_name='medicao',
            name='tipoMedicaoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.TipoMedicao'),
        ),
        migrations.AddField(
            model_name='apartamento',
            name='edificioId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.Edificio'),
        ),
    ]
